import type { Metadata } from "next";
import {Cormorant_Garamond, Inter, Poppins} from "next/font/google";
import "./globals.css";
import {NextUIProvider} from "@nextui-org/react";
import {Providers} from "@/app/provider";
import Header from "@/public/Header/Header";
import React from "react";
const cormorantGaramond = Cormorant_Garamond({
    subsets: ["latin"],
    variable: "--font-cormorant-garamond",
    weight: ["400"],
})

const poppins = Poppins({
    subsets: ["latin"],
    variable: "--font-poppins",
    weight: ["400", "600"],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cormorantGaramond.variable} ${poppins.variable}`}>
        <Providers>
            <Header/>
            {children}
        </Providers>
      </body>
    </html>
  );
}
